swagger: '2.0'
info:
  version: V0.2
  title: Word list management
  description: This API manages a Word list that will be part of a learning API
  contact:
    name: Pascal Amyot
    email: pascal.amyot@gmail.com
host: api.learn.com
basePath: /V1
schemes:
  - https
produces:
  - application/json
paths:
  /wordList:
    post:
      description: Create a new word list.
      parameters:
        - name: wordList
          in: body
          description: word list
          schema:
            $ref: '#/definitions/WordList'
      responses:
        '200':
          description: OK
definitions:
  Word:
    type: string
    title: name
  WordList:
    type: object
    properties:
      id:
        type: integer
        format: int64
        title: Word list ID
      words:
        type: array
        title: Words
        items:
          $ref: '#/definitions/Word'